# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ea2132510e1b6be07f99fe9fa3f33f64fecc38bf6f86648f5288cf1312c5ed14e31f3fcf22e5145bea4e3a2784b595c44a4f270dccac3bd38aa2ff2b0f9cc4

test:
  secret_key_base: 48a29ea2c3bb061bb02fbebc0039acf15879611efe7c34883cadc67840725ca4236776c135dab8fbd8305037b1d4c493d8f443eedc1a965e84d00c9147d7d6ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
